linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

run:
  timeout: 5m
  skip-dirs:
    - scratch
    - data
    - cmd/integration-test-utility

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - staticcheck