github: &github
  private_key: ((github.private_key))

resources:
  - name: git-main
    type: git
    icon: source-branch
    source:
      uri: git@github.com:EENCloud/bridge-devices-pos.git
      branch: main
      <<: *github

  - name: harbor
    type: registry-image
    icon: docker
    source:
      repository: harbor.eencloud.com/bridge/bridge-devices-pos
      tag: latest
      username: ((harbor.username))
      password: ((harbor.password))

jobs:
  - name: build-latest
    plan:
      - get: git-main
        trigger: true

      - task: build-main
        file: git-main/concourse/build-task.yml
        privileged: true
        input_mapping:
          bridge-devices-pos: git-main

      - put: harbor
        params:
          image: image/image.tar


